language: python
python:
  - "3.6"
install:
  - pip install -r ./app/requirements.txt
before_script:
  - chmod a+x ./app/helpers/test_string_helper.py
script:
  - app/helpers/test_string_helper.py
after_success:
  - docker login -u $DOCKER_UNAME -p $DOCKER_PASS
  - export REPO=selcukusta/basic-flask-sample
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO